//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Fox.GameKit
{
    public partial class OpticalCamo : Fox.Core.Data 
    {
        // Properties
        public EntityHandle target { get; set; }
        
        public bool isOn { get; set; }
        
        public Color lightBendColor { get; set; }
        
        public uint lightBendUOffset { get; set; }
        
        public uint lightBendVOffset { get; set; }
        
        // PropertyInfo
        private static EntityInfo classInfo;
        public static new EntityInfo ClassInfo
        {
            get
            {
                return classInfo;
            }
        }
        public override EntityInfo GetClassEntityInfo()
        {
            return classInfo;
        }
        static OpticalCamo()
        {
            classInfo = new EntityInfo(new String("OpticalCamo"), base.GetClassEntityInfo(), 0, "Camouflage", 0);
			
			classInfo.StaticProperties.Insert(new String("target"), new PropertyInfo(PropertyInfo.PropertyType.EntityHandle, 120, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("isOn"), new PropertyInfo(PropertyInfo.PropertyType.Bool, 128, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("lightBendColor"), new PropertyInfo(PropertyInfo.PropertyType.Color, 144, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("lightBendUOffset"), new PropertyInfo(PropertyInfo.PropertyType.UInt32, 160, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("lightBendVOffset"), new PropertyInfo(PropertyInfo.PropertyType.UInt32, 164, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
        }

        // Constructor
		public OpticalCamo(ulong address, ushort idA, ushort idB) : base(address, idA, idB) { }
        
        public override void SetProperty(String propertyName, Value value)
        {
            switch(propertyName.CString())
            {
                case "target":
                    this.target = value.GetValueAsEntityHandle();
                    return;
                case "isOn":
                    this.isOn = value.GetValueAsBool();
                    return;
                case "lightBendColor":
                    this.lightBendColor = value.GetValueAsColor();
                    return;
                case "lightBendUOffset":
                    this.lightBendUOffset = value.GetValueAsUInt32();
                    return;
                case "lightBendVOffset":
                    this.lightBendVOffset = value.GetValueAsUInt32();
                    return;
                default:
				    
                    base.SetProperty(propertyName, value);
                    return;
            }
        }
        
        public override void SetPropertyElement(String propertyName, ushort index, Value value)
        {
            switch(propertyName.CString())
            {
                default:
					
                    base.SetPropertyElement(propertyName, index, value);
                    return;
            }
        }
        
        public override void SetPropertyElement(String propertyName, String key, Value value)
        {
            switch(propertyName.CString())
            {
                default:
					
                    base.SetPropertyElement(propertyName, key, value);
                    return;
            }
        }
    }
}