//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tpp.Collectible
{
    public partial class TppPickableLocatorParameter : Fox.Core.DataElement 
    {
        // Properties
        public uint equipIdStrCode32 { get; set; }
        
        public ushort countRaw { get; set; }
        
        public ushort countSubRaw { get; set; }
        
        public ushort flag { get; set; }
        
        public ushort reserved { get; set; }
        
        // PropertyInfo
        private static EntityInfo classInfo;
        public static new EntityInfo ClassInfo
        {
            get
            {
                return classInfo;
            }
        }
        public override EntityInfo GetClassEntityInfo()
        {
            return classInfo;
        }
        static TppPickableLocatorParameter()
        {
            classInfo = new EntityInfo(new String("TppPickableLocatorParameter"), base.GetClassEntityInfo(), 40, null, 0);
			
			classInfo.StaticProperties.Insert(new String("equipIdStrCode32"), new PropertyInfo(PropertyInfo.PropertyType.UInt32, 56, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.Never, PropertyInfo.PropertyExport.Never, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("countRaw"), new PropertyInfo(PropertyInfo.PropertyType.UInt16, 60, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.Never, PropertyInfo.PropertyExport.Never, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("countSubRaw"), new PropertyInfo(PropertyInfo.PropertyType.UInt16, 62, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.Never, PropertyInfo.PropertyExport.Never, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("flag"), new PropertyInfo(PropertyInfo.PropertyType.UInt16, 64, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.Never, PropertyInfo.PropertyExport.Never, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("reserved"), new PropertyInfo(PropertyInfo.PropertyType.UInt16, 66, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.Never, PropertyInfo.PropertyExport.Never, null, null, PropertyInfo.PropertyStorage.Instance));
        }

        // Constructor
		public TppPickableLocatorParameter(ulong address, ushort idA, ushort idB) : base(address, idA, idB) { }
        
        public override void SetProperty(String propertyName, Value value)
        {
            switch(propertyName.CString())
            {
                case "equipIdStrCode32":
                    this.equipIdStrCode32 = value.GetValueAsUInt32();
                    return;
                case "countRaw":
                    this.countRaw = value.GetValueAsUInt16();
                    return;
                case "countSubRaw":
                    this.countSubRaw = value.GetValueAsUInt16();
                    return;
                case "flag":
                    this.flag = value.GetValueAsUInt16();
                    return;
                case "reserved":
                    this.reserved = value.GetValueAsUInt16();
                    return;
                default:
				    
                    base.SetProperty(propertyName, value);
                    return;
            }
        }
        
        public override void SetPropertyElement(String propertyName, ushort index, Value value)
        {
            switch(propertyName.CString())
            {
                default:
					
                    base.SetPropertyElement(propertyName, index, value);
                    return;
            }
        }
        
        public override void SetPropertyElement(String propertyName, String key, Value value)
        {
            switch(propertyName.CString())
            {
                default:
					
                    base.SetPropertyElement(propertyName, key, value);
                    return;
            }
        }
    }
}