//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Fox.Sdx
{
    public partial class SoundSource : Fox.Core.TransformData 
    {
        // Properties
        public String eventName { get; set; }
        
        public System.Collections.Generic.IList<EntityLink> shapes { get; } = new System.Collections.Generic.List<EntityLink>();
        
        public float lodRange { get; set; }
        
        public float playRange { get; set; }
        
        // PropertyInfo
        private static EntityInfo classInfo;
        public static new EntityInfo ClassInfo
        {
            get
            {
                return classInfo;
            }
        }
        public override EntityInfo GetClassEntityInfo()
        {
            return classInfo;
        }
        static SoundSource()
        {
            classInfo = new EntityInfo(new String("SoundSource"), base.GetClassEntityInfo(), 288, "Sound", 2);
			
			classInfo.StaticProperties.Insert(new String("eventName"), new PropertyInfo(PropertyInfo.PropertyType.String, 304, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("shapes"), new PropertyInfo(PropertyInfo.PropertyType.EntityLink, 312, 1, PropertyInfo.ContainerType.DynamicArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("lodRange"), new PropertyInfo(PropertyInfo.PropertyType.Float, 328, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("playRange"), new PropertyInfo(PropertyInfo.PropertyType.Float, 332, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
        }

        // Constructor
		public SoundSource(ulong address, ushort idA, ushort idB) : base(address, idA, idB) { }
        
        public override void SetProperty(String propertyName, Value value)
        {
            switch(propertyName.CString())
            {
                case "eventName":
                    this.eventName = value.GetValueAsString();
                    return;
                case "lodRange":
                    this.lodRange = value.GetValueAsFloat();
                    return;
                case "playRange":
                    this.playRange = value.GetValueAsFloat();
                    return;
                default:
				    
                    base.SetProperty(propertyName, value);
                    return;
            }
        }
        
        public override void SetPropertyElement(String propertyName, ushort index, Value value)
        {
            switch(propertyName.CString())
            {
                case "shapes":
                    while(this.shapes.Count <= index) { this.shapes.Add(default(EntityLink)); }
                    this.shapes[index] = value.GetValueAsEntityLink();
                    return;
                default:
					
                    base.SetPropertyElement(propertyName, index, value);
                    return;
            }
        }
        
        public override void SetPropertyElement(String propertyName, String key, Value value)
        {
            switch(propertyName.CString())
            {
                default:
					
                    base.SetPropertyElement(propertyName, key, value);
                    return;
            }
        }
    }
}