//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tpp.GameCore
{
    public partial class TppHeli2Parameter : Fox.Core.DataElement 
    {
        // Properties
        public StringMap<FilePtr<File>> partsFiles { get; } = new StringMap<FilePtr<File>>();
        
        public StringMap<FilePtr<File>> fmdlFiles { get; } = new StringMap<FilePtr<File>>();
        
        public StringMap<FilePtr<File>> fcnpFiles { get; } = new StringMap<FilePtr<File>>();
        
        public StringMap<FilePtr<File>> gsklFiles { get; } = new StringMap<FilePtr<File>>();
        
        public StringMap<FilePtr<File>> vfxFiles { get; } = new StringMap<FilePtr<File>>();
        
        public StringMap<FilePtr<File>> fovaFiles { get; } = new StringMap<FilePtr<File>>();
        
        public FilePtr<File> mtarFile { get; set; }
        
        // PropertyInfo
        private static EntityInfo classInfo;
        public static new EntityInfo ClassInfo
        {
            get
            {
                return classInfo;
            }
        }
        public override EntityInfo GetClassEntityInfo()
        {
            return classInfo;
        }
        static TppHeli2Parameter()
        {
            classInfo = new EntityInfo(new String("TppHeli2Parameter"), base.GetClassEntityInfo(), 344, null, 2);
			
			classInfo.StaticProperties.Insert(new String("partsFiles"), new PropertyInfo(PropertyInfo.PropertyType.FilePtr, 56, 1, PropertyInfo.ContainerType.StringMap, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("fmdlFiles"), new PropertyInfo(PropertyInfo.PropertyType.FilePtr, 104, 1, PropertyInfo.ContainerType.StringMap, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("fcnpFiles"), new PropertyInfo(PropertyInfo.PropertyType.FilePtr, 152, 1, PropertyInfo.ContainerType.StringMap, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("gsklFiles"), new PropertyInfo(PropertyInfo.PropertyType.FilePtr, 200, 1, PropertyInfo.ContainerType.StringMap, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("vfxFiles"), new PropertyInfo(PropertyInfo.PropertyType.FilePtr, 248, 1, PropertyInfo.ContainerType.StringMap, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("fovaFiles"), new PropertyInfo(PropertyInfo.PropertyType.FilePtr, 296, 1, PropertyInfo.ContainerType.StringMap, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("mtarFile"), new PropertyInfo(PropertyInfo.PropertyType.FilePtr, 344, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
        }

        // Constructor
		public TppHeli2Parameter(ulong address, ushort idA, ushort idB) : base(address, idA, idB) { }
        
        public override void SetProperty(String propertyName, Value value)
        {
            switch(propertyName.CString())
            {
                case "mtarFile":
                    this.mtarFile = value.GetValueAsFilePtr();
                    return;
                default:
				    
                    base.SetProperty(propertyName, value);
                    return;
            }
        }
        
        public override void SetPropertyElement(String propertyName, ushort index, Value value)
        {
            switch(propertyName.CString())
            {
                default:
					
                    base.SetPropertyElement(propertyName, index, value);
                    return;
            }
        }
        
        public override void SetPropertyElement(String propertyName, String key, Value value)
        {
            switch(propertyName.CString())
            {
                case "partsFiles":
                    this.partsFiles.Add(key, value.GetValueAsFilePtr());
                    return;
                case "fmdlFiles":
                    this.fmdlFiles.Add(key, value.GetValueAsFilePtr());
                    return;
                case "fcnpFiles":
                    this.fcnpFiles.Add(key, value.GetValueAsFilePtr());
                    return;
                case "gsklFiles":
                    this.gsklFiles.Add(key, value.GetValueAsFilePtr());
                    return;
                case "vfxFiles":
                    this.vfxFiles.Add(key, value.GetValueAsFilePtr());
                    return;
                case "fovaFiles":
                    this.fovaFiles.Add(key, value.GetValueAsFilePtr());
                    return;
                default:
					
                    base.SetPropertyElement(propertyName, key, value);
                    return;
            }
        }
    }
}