//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tpp.GameKit
{
    public partial class TppObjectBrushPluginBush : Fox.GameKit.ObjectBrushPluginClone 
    {
        // Properties
        public uint reservedCount { get; set; }
        
        public float upgradeLodRateForHighEnd { get; set; }
        
        public EntityPtr<TppGameKit.ObjectBrushPluginBushDataElement> gimmickParameter { get; set; }
        
        public EntityLink externalGimmickParameter { get; set; }
        
        // PropertyInfo
        private static EntityInfo classInfo;
        public static new EntityInfo ClassInfo
        {
            get
            {
                return classInfo;
            }
        }
        public override EntityInfo GetClassEntityInfo()
        {
            return classInfo;
        }
        static TppObjectBrushPluginBush()
        {
            classInfo = new EntityInfo(new String("TppObjectBrushPluginBush"), base.GetClassEntityInfo(), 168, null, 3);
			
			classInfo.StaticProperties.Insert(new String("reservedCount"), new PropertyInfo(PropertyInfo.PropertyType.UInt32, 184, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("upgradeLodRateForHighEnd"), new PropertyInfo(PropertyInfo.PropertyType.Float, 188, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, null, null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("gimmickParameter"), new PropertyInfo(PropertyInfo.PropertyType.EntityPtr, 192, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorAndGame, PropertyInfo.PropertyExport.EditorAndGame, typeof(TppGameKit.ObjectBrushPluginBushDataElement), null, PropertyInfo.PropertyStorage.Instance));
			classInfo.StaticProperties.Insert(new String("externalGimmickParameter"), new PropertyInfo(PropertyInfo.PropertyType.EntityLink, 200, 1, PropertyInfo.ContainerType.StaticArray, PropertyInfo.PropertyExport.EditorOnly, PropertyInfo.PropertyExport.EditorOnly, null, null, PropertyInfo.PropertyStorage.Instance));
        }

        // Constructor
		public TppObjectBrushPluginBush(ulong address, ushort idA, ushort idB) : base(address, idA, idB) { }
        
        public override void SetProperty(String propertyName, Value value)
        {
            switch(propertyName.CString())
            {
                case "reservedCount":
                    this.reservedCount = value.GetValueAsUInt32();
                    return;
                case "upgradeLodRateForHighEnd":
                    this.upgradeLodRateForHighEnd = value.GetValueAsFloat();
                    return;
                case "gimmickParameter":
                    this.gimmickParameter = EntityPtr<TppGameKit.ObjectBrushPluginBushDataElement>.Get(value.GetValueAsEntityPtr().Entity as TppGameKit.ObjectBrushPluginBushDataElement);
                    return;
                case "externalGimmickParameter":
                    this.externalGimmickParameter = value.GetValueAsEntityLink();
                    return;
                default:
				    
                    base.SetProperty(propertyName, value);
                    return;
            }
        }
        
        public override void SetPropertyElement(String propertyName, ushort index, Value value)
        {
            switch(propertyName.CString())
            {
                default:
					
                    base.SetPropertyElement(propertyName, index, value);
                    return;
            }
        }
        
        public override void SetPropertyElement(String propertyName, String key, Value value)
        {
            switch(propertyName.CString())
            {
                default:
					
                    base.SetPropertyElement(propertyName, key, value);
                    return;
            }
        }
    }
}